// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvphBkVbT7gIMCxeX4Jo1Ci235RwptGS8',
    appId: '1:996794007271:web:ee901a106603f2dddc6c42',
    messagingSenderId: '996794007271',
    projectId: 'gui-app-f9c0c',
    authDomain: 'gui-app-f9c0c.firebaseapp.com',
    databaseURL: 'https://gui-app-f9c0c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gui-app-f9c0c.appspot.com',
    measurementId: 'G-RMCVTR7F14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvphBkVbT7gIMCxeX4Jo1Ci235RwptGS8',
    appId: '1:996794007271:web:c9b9f25507a8a161dc6c42',
    messagingSenderId: '996794007271',
    projectId: 'gui-app-f9c0c',
    authDomain: 'gui-app-f9c0c.firebaseapp.com',
    databaseURL: 'https://gui-app-f9c0c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gui-app-f9c0c.appspot.com',
    measurementId: 'G-82C4FGZXQE',
  );

}